### ISSUE TITLE
ES6 cannot be parsed

### ISSUE THREAD

**Issue by anilanar** [th0r/webpack-bundle-analyzer#104]
#### Issue description
I'm saying ES6 because I'm not sure what goes into ES2015, 2016 or 2017.

In the project I'm working on, we started doing 2 builds, 1 using `babel-preset-env` targeting IE11, another targeting modern browsers such as Safari 10.1, Chrome 59 etc. For the latter, webpack bundle analyzer complains about not being able to parse. It could be async/await syntax which is in Stage 3. Could you perhaps add async/await plugin for acorn?

#### Technical info
* Webpack Bundle Analyzer version: 2.8.2
* Webpack version: 2.4.1
* Node.js version: 7.10.0
* npm/yarn version: irrelevant
* OS: MacOS

#### Debug info
How do you use this module? As CLI utility or as plugin?
Plugin

If CLI, what command was used? (e.g. `webpack-bundle-analyzer -O path/to/stats.json`)

If plugin, what options were provided? (e.g. `new BundleAnalyzerPlugin({ analyzerMode: 'disabled', generateStatsFile: true })`)
```
           {
                        analyzerMode: 'static',
                        reportFilename: ' a path here',
                        generateStatsFile: true,
                        statsFilename: 'a path here'
           }
```

What other Webpack plugins were used?
There are 2 differences between two builds:
- babel-preset-env targets different browsers
- UglifyJS plugin vs Babili webpack plugin

**Comment by th0r** [comment]
Webpack Bundle Analyzer version: ?

**Comment by anilanar** [comment]
Added, you were too fast to answer, I was still editing my question. Thanks ❤️

**Comment by th0r** [comment]
Try 2.8.3 - it should be [fixed there](https://github.com/th0r/webpack-bundle-analyzer/blob/master/CHANGELOG.md#283)

**Comment by anilanar** [comment]
I've checked the source code already, acorn doesn't handle `async/await` without a plugin. Acorn only handles Stage 4 specs.

**Comment by th0r** [comment]
We have a [test](https://github.com/th0r/webpack-bundle-analyzer/blob/master/test/bundles/validBundleWithEsNextFeatures.js#L2) for it. It passes. Can you just check it?

**Comment by anilanar** [comment]
Upgrading worked. Thanks a lot.
