### ISSUE TITLE
Can I config whether open browser automatically?  

### ISSUE THREAD

**Issue by NE-SmallTown** [th0r/webpack-bundle-analyzer#105]
#### Issue description

For now if I use this plugin it will open the browser automatically, but I think it would be better to open it when I enter the url. I find [viewer.js#L29](https://github.com/th0r/webpack-bundle-analyzer/blob/master/src/viewer.js#L29) has a param `openBrowser` but not listed in the option of README, I am not sure it will works. Do you have any thought about this?

**Comment by th0r** [comment]
The option is called `openAnalyzer` and it's mentioned on the main page.

**Comment by NE-SmallTown** [comment]
Sorry,I missed it
