### ISSUE TITLE
Details of dependencies lost in visual report

### ISSUE THREAD

**Issue by coryrylan** [th0r/webpack-bundle-analyzer#106]
#### Issue description
It looks like with the latest webpack the the module output changed to where the analyzer cannot drill down into the dependencies. Not quite sure where to start looking but going to try to debug it this weekend. 

![capture](https://user-images.githubusercontent.com/2021067/28723491-836c954c-737c-11e7-8a91-da0bd0309089.PNG)
#### Technical info
* Webpack Bundle Analyzer version: 2.8.3
* Webpack version: 3.4.1
* Node.js version: 8.1.4
* npm/yarn version: 3.10.9
* OS: Windows 10 

#### Debug info
How do you use this module? As CLI utility or as plugin?
CLI

If CLI, what command was used? (e.g. `webpack-bundle-analyzer -O path/to/stats.json`)
`webpack-bundle-analyzer dist/client/stats.json`

What other Webpack plugins were used?
Use Angular CLI v1.2.6

**Comment by kuncevic** [comment]
It was just being fixed with this https://github.com/angular/angular-cli/pull/7259

**Comment by th0r** [comment]
Nice!
