### ISSUE TITLE
Fails when trying to get sizes for sourceMaps

### ISSUE THREAD

**Issue by guzart** [th0r/webpack-bundle-analyzer#11]
Throws an error when an external sourceMap file (*.map.js) is part of the stats.json. I believe the problem is when [acorn is trying to parse](https://github.com/th0r/webpack-bundle-analyzer/blob/7b72a2bc5a6484a4695eec6de349323c3f2929ce/src/parseUtils.js#L11) the file.

This could easily be fixed by ignoring all sourceMap files, but am not sure if this is the right approach.

**Comment by th0r** [comment]
Well, `js` is a strange extension for sourcemap. It should be `map`, or something like that.

**Comment by guzart** [comment]
Indeed

**Comment by th0r** [comment]
But I could make logic more bulletproof though...

**Comment by guzart** [comment]
I don't think there's a need to do that, you are right a sourceMap file should not have a `.js` extension since it's not a valid JavaScript file. Just updated my webpack.config.js, Thanks.
