### ISSUE TITLE
this.state.checkedItems.includes

### ISSUE THREAD

**Issue by lmw6412036** [th0r/webpack-bundle-analyzer#111]
Uncaught TypeError: this.state.checkedItems.includes is not a function

**Comment by valscion** [comment]
Could you send a screenshot or more details about when this happens?

**Comment by lmw6412036** [comment]
![tim 20170808155250](https://user-images.githubusercontent.com/18605751/29061659-5a08855c-7c51-11e7-97ab-a8d7607c3e8a.png)

**Comment by valscion** [comment]
Could you try another browser? Seems like you are using a browser that does not have `Array.prototype.includes` method that was added in ES2016 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

We could look into adding a polyfill for when this is missing.

**Comment by lmw6412036** [comment]
think you!

**Comment by valscion** [comment]
It works in another browser?

**Comment by lmw6412036** [comment]
@valscion yes，latest chrome

**Comment by valscion** [comment]
Great! Thanks for replying back. Have a great day!

**Comment by congzhou09** [comment]
@lmw6412036 我也用的360浏览器也不显示哈哈
