### ISSUE TITLE
How do you view the output once you run the CLI/install into webpack?

### ISSUE THREAD

**Issue by evolve2k** [th0r/webpack-bundle-analyzer#112]
Probably silly question but it wasn't obvious to me how to use this once I got it installed so was going to move on and try other approaches. 

Any tips for the less insightful would be great.

Thx

**Comment by valscion** [comment]
Hi! Glad you decided to try this out :)

We have tried to provide this information in the README.md. Would you happen to have any ideas how we could make that information more accessible?

It's difficult for us maintainers to write good documentation for the newcomer, as we know the library inside out. Your point of view of how the README.md could be improved is much appreciated

**Comment by evolve2k** [comment]
Sure, I'm happy to contribute to the README once I understand the answer.

Ok lets try from here.

Say I follow the CLI approach and run
$ webpack --profile --json | Out-file 'stats.json' -Encoding OEM

So I'm guessing I now have a file stats.json that has been created.

What do I do next to then bring up the visual graphic in by browser?

**Comment by valscion** [comment]
Ok, so based on your pasted code example, are you using Windows PowerShell?

Next up you should be running `webpack-bundle-analyzer --help` to show usage information.

**Comment by valscion** [comment]
I'm gonna close this issue due to inactivity, but feel free to send a new message here and I can reopen if needed, @evolve2k ☺️
