### ISSUE TITLE
npm install ejs needed

### ISSUE THREAD

**Issue by luckylooke** [th0r/webpack-bundle-analyzer#13]
During "npm instal" ejs is listed, but when I ran webpack it fails on `Error: Cannot find module 'ejs'`, so I tried to install ejs manually "npm i ejs" and it works now. Probably some issue with ejs project it self. But at least you should know about this. Thaks for your great tool btw ;)

**Comment by th0r** [comment]
It's some npm bug. Try to update npm and do `rm - rf node_modules && npm i`

**Comment by luckylooke** [comment]
might be, but it was on fresh install
