### ISSUE TITLE
Show correct bundle size after minifications/optimizations

### ISSUE THREAD

**Issue by boa86** [th0r/webpack-bundle-analyzer#15]
It''d be very helpfull to see actual size of the bundle (and each part) after any minification/optimization plugins were applyed.
Main reason - some code might be removed, merged and agressive minified. And it might great change overall sizes map.
Currently, it shows bundle parts sizes likely before minification/optimization.

Also, it'd be great, if webpack-bundle-analyzer were able to show actual info depend on which place it was placed in the "pluguns" array (before or after some plugins)

I have next "plugins" array:
`plugins: [

    // Define free variables
    // https://webpack.github.io/docs/list-of-plugins.html#defineplugin
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': isDebug ? '"development"' : '"production"',
      'process.env.BROWSER': true,
      __DEV__: isDebug,
    }),

    // Emit a file with assets paths
    // https://github.com/sporto/assets-webpack-plugin#options
    new AssetsPlugin({
      path: path.resolve(__dirname, '../build'),
      filename: 'assets.js',
      processOutput: x => `module.exports = ${JSON.stringify(x)};`,
    }),

    // Assign the module and chunk ids by occurrence count
    // Consistent ordering of modules required if using any hashing ([hash] or [chunkhash])
    // https://webpack.github.io/docs/list-of-plugins.html#occurrenceorderplugin
    new webpack.optimize.OccurrenceOrderPlugin(true),

    ...isDebug ? [] : [
      // Search for equal or similar files and deduplicate them in the output
      // https://webpack.github.io/docs/list-of-plugins.html#dedupeplugin
      new webpack.optimize.DedupePlugin(),

      // Minimize all JavaScript output of chunks
      // https://github.com/mishoo/UglifyJS2#compressor-options
      new webpack.optimize.UglifyJsPlugin({
        compress: {
          screw_ie8: true,
          warnings: isVerbose,
        },
      }),
    ],

    // Webpack plugin and CLI utility that represents bundle
    // content as convenient interactive zoomable treemap
    // https://github.com/th0r/webpack-bundle-analyzer
    new BundleAnalyzerPlugin({
      // Can be `server`, `static` or `disabled`.
      // In `server` mode analyzer will start HTTP server to show bundle report.
      // In `static` mode single HTML file with bundle report will be generated.
      // In `disabled` mode you can use this plugin to just generate
      // Webpack Stats JSON file by setting `generateStatsFile` to `true`.
      analyzerMode: isReport ? 'static' : 'disabled',
      // Port that will be used by in `server` mode to start HTTP server.
      analyzerPort: 8888,
      // Path to bundle report file that will be generated in `static` mode.
      // If relative path is provided, it will be relative to bundles output directory
      reportFilename: 'ui-report.html',
      // Automatically open report in default browser
      openAnalyzer: isReport,
      // If `true`, Webpack Stats JSON file will be generated in bundles output directory
      generateStatsFile: false,
      // Name of Webpack Stats JSON file that will be generated if `generateStatsFile` is `true`.
      // Relative to bundles output directory.
      statsFilename: 'ui-stats.json',
    }),
  ],`

**Comment by th0r** [comment]
@boa86 Analyzer tries to parses your bundles (even minified) and show two sizes in tooltip: `Stat size` and `Parsed size`.
The first one is the size taken from webpack stats json file and the second one is the actual parsed size of a module from generated bundle.

![webpack bundle analyzer zoomable treemap](https://cloud.githubusercontent.com/assets/302213/19711973/908ae002-9b42-11e6-8471-bc8e9ab6dec7.gif)

If you see only `Stat size` then either something went wrong and analyzer couldn't parse your bundles or it just couldn't find them.

**Comment by boa86** [comment]
Thank you for quick report!
You are right. I have experimented with enabling/disabling some of plugins and really found that OccurrenceOrderPlugin damage stat data
https://webpack.github.io/docs/list-of-plugins.html#occurrenceorderplugin

**Comment by th0r** [comment]
> found that OccurrenceOrderPlugin damage stat data

What do you mean? Do you have any problem with it?

**Comment by boa86** [comment]
yes, webpack-bundle-analyzer doen't show minified statistics if this plugin is enabled. I have not yet tested it with other webpack configs (will do it later).
Do you have the same behaviour for this case?

**Comment by th0r** [comment]
I use `OccurrenceOrderPlugin` in one of my projects and analyzer parses bundles as it should.
You're saying that if you add `OccurrenceOrderPlugin` you can't see `Parsed size` in the generated report?
Is there anything in console?

**Comment by okovpashko** [comment]
I have the same issue when I run webpack-bundle-analyzer as CLI tool. 
I got both parsed and stat sizes only when I added analyzer as a plugin with analyzerMode: 'static'.

In 'server' mode I get error after report opened in browser.
`Error: ENOENT: no such file or directory, open '/projectdir/node_modules/webpack-bundle-analyzer/views/('style', { filename: 'viewer.css' })'`

**Comment by abierbaum** [comment]
@th0r It was kind of implied above, but is the parsed sized (ie. minified, shaken, etc) the size that is used for the visualization?

**Comment by abierbaum** [comment]
@th0r Just double checked and I am not seeing parsed size in my output either.

I get the following output at the end of the build:

```
<previous lines cut>
4164ms chunk asset optimization
2617ms asset optimization
 95% emitting

Unable to find bundle asset "/home/allenb/Source/taccs/web2/dist/vendor.bundle.js".
Analyzer will use module sizes from stats file.

Webpack Bundle Analyzer saved report to /home/allenb/Source/taccs/web2/dist/size_report.html

158ms emitting
Hash: dc86743694aa26b092d2
Version: webpack 2.1.0-beta.25
Time: 24923ms
                          Asset       Size  Chunks             Chunk Names
  fonts/fontawesome-webfont.eot    76.5 kB          [emitted]  
               vendor.bundle.js    8.75 MB       0  [emitted]  vendor
          install_app.bundle.js    3.16 MB       2  [emitted]  install_app
        pwd_reset_app.bundle.js    5.68 kB       3  [emitted]  pwd_reset_app
            polyfills.bundle.js     735 kB       4  [emitted]  polyfills
           assets/icon/.gitkeep    0 bytes          [emitted]  
        assets/icon/favicon.ico    1.15 kB          [emitted]  
              site_overrides.js  380 bytes          [emitted]  
            admin_app.bundle.js    3.35 MB       1  [emitted]  admin_app
  fonts/fontawesome-webfont.ttf     153 kB          [emitted]  
 fonts/fontawesome-webfont.woff    90.4 kB          [emitted]  
fonts/fontawesome-webfont.woff2    71.9 kB          [emitted]  
  fonts/fontawesome-webfont.svg     392 kB          [emitted]  
          fonts/FontAwesome.otf     125 kB          [emitted]  
                     index.html  668 bytes          [emitted]  
            client_install.html  678 bytes          [emitted]  
            password_reset.html  690 bytes          [emitted]  
 [672] ./src async 160 bytes {0} [built]
       [] -> factory:12ms building:14ms = 26ms
[1233] multi admin_app 28 bytes {1} [built]
        factory:0ms building:1ms = 1ms
[1234] multi install_app 28 bytes {2} [built]
        factory:0ms building:0ms = 0ms
[1235] multi pwd_reset_app 28 bytes {3} [built]
        factory:0ms building:1ms = 1ms
    + 1232 hidden modules
Child html-webpack-plugin for "index.html":
        + 4 hidden modules
Child html-webpack-plugin for "client_install.html":
        + 4 hidden modules
Child html-webpack-plugin for "password_reset.html":
        + 4 hidden modules

```
The vendor.bundle.js file exists at that absolute location after the build is complete.  I do not know if it exists at the time that bundle analyzer is attempting to load it.

I am using webpack 2.1.0-beta.25 and running a build with multiple entrypoints and bundles.

The config for bundle analyzer is:

```
 new BundleAnalyzerPlugin({
       analyzerMode: 'static',
       reportFilename: 'size_report.html',
       openAnalyzer: false
    })
```

Anything I can do to help debug this further?

**Comment by th0r** [comment]
@abierbaum Released `v1.5.1`. It should be fixed there.

**Comment by abierbaum** [comment]
@th0r Worked great.  Thanks!!!

**Comment by th0r** [comment]
> In 'server' mode I get error after report opened in browser.
> Error: ENOENT: no such file or directory, open '/projectdir/node_modules/webpack-bundle-analyzer/views/('style', { filename: 'viewer.css' })'

@okovpashko This is reeaaally strange thing. Can you try `v1.5.2` and fresh `node_modules` install?

**Comment by th0r** [comment]
@boa86 Can you try the latest version?

**Comment by boa86** [comment]
@th0r Made build with the latest version. All works fine! 
Left sidebar very useful too :)
This issue is closed for my case. Thank you!

**Comment by dylanjha** [comment]
@th0r  - could you please elaborate here:

> Analyzer tries to parse your bundles (even minified) and show two sizes in tooltip: Stat size and Parsed size.
> The first one is the size taken from webpack stats json file and the second one is the actual parsed size of a module from generated bundle.

What does it mean when Stat size and Parsed size are different? If I'm trying to decrease bundle size which one should I be looking at?

Thank you for this tool 👍

**Comment by valscion** [comment]
Parsed size is the one after minification. Stat size is the size of your original modules, before minification.

So you should be looking at parsed size if you want to decrease bundle size.

Stat size might have dead code that gets eliminated with minification, e.g. React package size will be very different if you run it minification and `NODE_ENV=production` than without.

**Comment by williamle8300** [comment]
Why is the parsed size (e.g., the minified) larger file size than non-minified? Shouldn't it be vice-versa?

**Comment by th0r** [comment]
@williamle8300 should be if it's really minified.

**Comment by AndrewSouthpaw** [comment]
Amazing tool!

Unfortunately, the parsed size isn't showing up for me. I'm running `2.9.2`, and I'm not seeing any errors in the output. Any pointers on what might be going wrong?

**Comment by AndrewSouthpaw** [comment]
For those still having issues getting the `parsed` info: make sure you're not running `webpack-dev-server`, because then it won't work correctly. It's easy to do when you have a shortcut to start your dev environment. 😅
