### ISSUE TITLE
Server mode error if nightwatch is installed in the project

### ISSUE THREAD

**Issue by okovpashko** [th0r/webpack-bundle-analyzer#17]
Running analyzer in server mode causes an express error
`Error: ENOENT: no such file or directory, open '/Users/sandro/Documents/PersonalProjects/webpack-bunle-analyzer-ejs/node_modules/webpack-bundle-analyzer/views/('style', { filename: 'viewer.css' })'`
if project has nightwatch as a dependency.

I found that nightwatch also has ejs as a dependency but version 0.8.3 from https://github.com/tj/ejs. It's installed by NPM in the root of project's node_modules. 

ejs 2.5.2 (https://github.com/mde/ejs) required by webpack-bundle-analyzer is installed in node_modules/webpack-bundle-analyzer/node_modules.

I haven't figured out why but looks like express tries to use ejs from project's node_modules and that version has incompatible `include` syntax.

**Comment by th0r** [comment]
Wow! Thanks for investigation! Will fix it as soon as possible.

**Comment by th0r** [comment]
`v1.5.3` should fix it.

**Comment by th0r** [comment]
Filled bug https://github.com/expressjs/express/issues/3124 about it

**Comment by okovpashko** [comment]
Thanks a lot for the fix!
