### ISSUE TITLE
Incompatible with webpack 2?

### ISSUE THREAD

**Issue by mvestergaard** [th0r/webpack-bundle-analyzer#18]
I'm trying to run this, but the page just starts up blank.

I can see that the chartData isn't set.
`window.chartData = [];`

Would it be safe to assume that this is because I'm using webpack 2?

**Comment by th0r** [comment]
A few guys I know use it with Webpack 2 and it works just fine.
How do you use it?
Can you generate stats file and show `assets` section from it?

**Comment by th0r** [comment]
Also, let continue in #10 - problem seems like yours.
