### ISSUE TITLE
noInfo property

### ISSUE THREAD

**Issue by pburtchaell** [th0r/webpack-bundle-analyzer#19]
What are your thoughts on including a `noInfo` property in the config? I imagine the default value would be `false`. It would be nice to turn off logs, such as this, from the plugin:

```
Webpack Bundle Analyzer is started at http://localhost:8888
Use Ctrl+C to close it
```

There are cases where one might not want additional information logged. 

Thanks!

**Comment by th0r** [comment]
What about errors?

**Comment by pburtchaell** [comment]
My aim would be to silence general info logs, but not errors.

**Comment by th0r** [comment]
Added `logLevel` option in `v2.1.0`
