### ISSUE TITLE
Cannot read property 'parsedSize'

### ISSUE THREAD

**Issue by konstantin24121** [th0r/webpack-bundle-analyzer#22]
Error in script.
Console said © Cannot read property 'parsedSize' of undefined

850: r.hasParsedSizes = "number" == typeof r.props.data[0].parsedSize,

**Comment by th0r** [comment]
What does `window.chartData` variable in generated report contain? Is it empty?

**Comment by konstantin24121** [comment]
totaly empty http://joxi.ru/xAeOogEiyZNkmy

**Comment by th0r** [comment]
Well, then I need all the information from issue template that you erased. It'll simply finding a bug. At least it would be nice to see your stats file.

**Comment by konstantin24121** [comment]
https://www.dropbox.com/sh/599ueqfbxq4715n/AACJlV949_dSR2C1m2lXFCtla?dl=0 my webpack config and two generated by WBA files

**Comment by th0r** [comment]
You use very strange template for bundle filenames: `filename: '[name].js?v=[hash]'`.
What webpack generates in this case? Does your generated bundle files have `?v=[hash]` in the name (e.g. `bundle.js?v=8c80fe52746c2c5eb82e`)?

**Comment by th0r** [comment]
The thing is analyzer filters out all non-js assets and your js bundles are filtered out as well because they don't have `.js` extension.

**Comment by th0r** [comment]
Should be fixed in `v2.0.1`

**Comment by konstantin24121** [comment]
@th0r  thanks!
