### ISSUE TITLE
TypeError: currentFolder.addFile is not a function

### ISSUE THREAD

**Issue by ghoshnirmalya** [th0r/webpack-bundle-analyzer#3]
Running into this issue:

```
Unable to find bundle asset "/filename_settings.js".
Analyzer will use module sizes from stats file.

Could't analyze webpack bundle:
TypeError: currentFolder.addFile is not a function
```

I just included `BundleAnalyzerPlugin`. My `webpack` bundle has multiple entry points and I'm only including the plugin by adding `new BundleAnalyzerPlugin()`.

My `webpack` version is `1.13.2`.

**Comment by th0r** [comment]
> Unable to find bundle asset "/filename.js"

It couldn't find your generated bundle files. Maybe you post-processing them somehow (renaming?)
Does "filename.js" exist in your output folder?

**Comment by th0r** [comment]
@ghoshnirmalya Have you solved your problem?

**Comment by ghoshnirmalya** [comment]
@th0r Will check and let you know in a day. Thanks.

**Comment by ghoshnirmalya** [comment]
I've the entry point as `filename_settings '` and it references `./admin/pages/filename-settings'`.

It's stating:

```
Unable to find bundle asset "/filename_settings.js".
Analyzer will use module sizes from stats file.

Could't analyze webpack bundle:
TypeError: currentFolder.addFile is not a function
```

**Comment by th0r** [comment]
> and it references ./admin/pages/filename-settings

What is `filename-settings` here? A file? `filename-settings.js`?

**Comment by ghoshnirmalya** [comment]
It is actually an entry point `entry: {}` for the webpack. It generates a bundled file named `filename-settings.js`.

**Comment by th0r** [comment]
What are the values for `output.path` and `output.filename` from your webpack config?
Can you also post contents of `assets` array from `stats.json` file?

**Comment by ghoshnirmalya** [comment]
```
output: {
    path: __dirname + '/dist/',
    filename: '[name].js'
  }
```

**Comment by ghoshnirmalya** [comment]
I'm not generating the `stats.json`. Should I try generating it?

**Comment by th0r** [comment]
> Should I try generating it?

It would help me a lot. Just use `generateStatsFile: true` option and it'll be generated next to your bundles.

**Comment by ghoshnirmalya** [comment]
It didn't generate a `stats.json` file. It showed the error `Could't analyze webpack bundle:...` and then got stuck at that only! Am I missing something here?

I required the plugin using:

`var BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;` 

and added the plugin like:

```
new BundleAnalyzerPlugin({
  generateStatsFile: true
})
```

**Comment by th0r** [comment]
Try upgrading to the latest `v1.4.1` and use this:
```js
new BundleAnalyzerPlugin({
  analyzerMode: 'disabled',
  generateStatsFile: true
})
```

**Comment by ghoshnirmalya** [comment]
I'm using `v1.4.1`.
When I added this code, it worked without any errors but when I checked `git status`, it didn't show me any `stats.json` file!

**Comment by th0r** [comment]
It should be in `dist` folder according to your webpack config.

**Comment by ghoshnirmalya** [comment]
It's not getting generated.

**Comment by th0r** [comment]
> It's not getting generated.

It's very strange. Have you tried `rm -rf node_modules && npm i`?

**Comment by ghoshnirmalya** [comment]
Yes. I've tried it.

**Comment by jiayihu** [comment]
I'm getting the same error:
```
Unable to find bundle asset "/js/main.js".
Analyzer will use module sizes from stats file.
```

My webpack (v 1.13.0) config is this:
```
output: {
    path: root.dest,
    publicPath: IS_DEV ? 'http://localhost:3000/' : '',
    filename: IS_DEV ? 'js/main.js' : '/js/main.js',
}
```

**Comment by th0r** [comment]
@jiayihu And what is `root.dest`?

**Comment by th0r** [comment]
> filename: IS_DEV ? 'js/main.js' : '/js/main.js'

@jiayihu What is the reason of starting `/` here?

**Comment by jiayihu** [comment]
@th0r to make it work with `react-router` when loading the `main.js`. For example to avoid `https://github.com/profile/my-route/main.js` if the file is located in `https://github.com/main.js`.

**Comment by th0r** [comment]
@jiayihu @ghoshnirmalya Can you try `v1.4.2`? I believe I fixed it there.

**Comment by jiayihu** [comment]
@th0r I confirm it's fixed for me 💥

**Comment by th0r** [comment]
@ghoshnirmalya Do you still have this issue with `v1.4.2`?

**Comment by ghoshnirmalya** [comment]
I can confirm it's not fixed for me :/

**Comment by th0r** [comment]
> I can confirm it's not fixed for me :/

Can you send me your stats file?

I've just released v1.5.0 with `statsOptions` option for analyzer plugin so you can exclude any sensitive information from generated stats file.
For example you can exclude module sources from it like that:
```js
new BundleAnalyzerPlugin({
  analyzerMode: 'disabled',
  generateStatsFile: true,
  statsOptions: { source: false }
})
```
I just don't know how to help you without it.
Ah, and one more question: what's your OS?

**Comment by ghoshnirmalya** [comment]
OS: Sierra

**Comment by th0r** [comment]
> Can you send me your stats file?
> 
> I've just released v1.5.0 with statsOptions option for analyzer plugin so you can exclude any sensitive information from generated stats file.

@ghoshnirmalya I won't be able to help you without it.

**Comment by okovpashko** [comment]
@th0r I described that error and its possible reason in #17

**Comment by th0r** [comment]
@ghoshnirmalya Can you try the latest version?

**Comment by ghoshnirmalya** [comment]
Sure.

**Comment by ghoshnirmalya** [comment]
`v2.0.0` fixed it for me. Thanks.
