### ISSUE TITLE
Feature Request: Nest modules by dependency graph instead of folder structure

### ISSUE THREAD

**Issue by sirlancelot** [th0r/webpack-bundle-analyzer#30]
This is a great tool! I really enjoy visualizations of my work. I think it would be neat if the treemap's nodes were only modules instead of following the folder structure. It might make the map more useful and you can already see the path when you mouseover the node.

**Comment by th0r** [comment]
But a module can be required by two different modules. How would you show that?

**Comment by th0r** [comment]
@sirlancelot Thoughts?

**Comment by sirlancelot** [comment]
I think I'd like to see it in both places. Not sure what makes the most sense. I'll have to think about it more. Webpack's own [Analyze](https://webpack.github.io/analyse/) tool is able to create a web but that may not work for the kind of visualization of this tool.

**Comment by th0r** [comment]
@sirlancelot For example, every react component imports react. How do you want it to be shown in a flat treemap?
What I'm trying to say is treemap is not suitable for many-to-many relationships like this.
