### ISSUE TITLE
Fix blurry rendering on HiDPI screens

### ISSUE THREAD

**Issue by jaydenseric** [th0r/webpack-bundle-analyzer#33]
The vendor library for drawing the chart (Carrot Search FoamTree) [by default configures devicePixelRatio to 1](https://get.carrotsearch.com/foamtree/latest/api/#pixelRatio). This looks really blurry for those of us with Retina, 4k, 5k or even better screens. Let's set this to be dynamic to the device using `window.devicePixelRatio`. It should be an easy tweak.

Also, it's a good idea to add `<meta name="viewport" content="width=device-width, initial-scale=1"/>` to the HTML. It seems to be missing.

**Comment by th0r** [comment]
Thanks for an issue! Fixed it in `v2.2.0`
