### ISSUE TITLE
How to use it with angular-cli project?

### ISSUE THREAD

**Issue by harilalinapp** [th0r/webpack-bundle-analyzer#43]
#### Issue description
...

#### Technical info
* Webpack Bundle Analyzer version:
* Webpack version:
* Node.js version:
* npm/yarn version:
* OS:

#### Debug info
How do you use this module? As CLI utility or as plugin?
would like to use as CLI utility. But can't create stats.json 

If CLI, what command was used? (e.g. `webpack-bundle-analyzer -O path/to/stats.json`)

If plugin, what options were provided? (e.g. `new BundleAnalyzerPlugin({ analyzerMode: 'disabled', generateStatsFile: true })`)

What other Webpack plugins were used?

It would be nice to also attach webpack stats file.
It can be generated using these options:
```js
new BundleAnalyzerPlugin({
  analyzerMode: 'disabled',
  generateStatsFile: true,
  // Excludes module sources from stats file so there won't be any sensitive data
  statsOptions: { source: false }
})`
```
`stats.json` will be created in Webpack bundle output directory.

**Comment by valscion** [comment]
I'm sorry but I don't understand what you are asking. I'd need you to fill in the issue description with much more detail and also provide the technical info.

**Comment by valscion** [comment]
> would like to use as CLI utility. But can't create stats.json

Is this your issue? ☝️ 

I have no knowledge about `angular-cli`. Does `angular-cli` allow you to define custom webpack configuration or add plugins?

**Comment by th0r** [comment]
@harilalinapp Be more specific please.

**Comment by chinchiheather** [comment]
You can generate the `stats.json` file using Angular-CLI and then use the command line webpack bundle analyzer
So you would run something like:
````
npm i --save-dev -g webpack-bundle-analyzer
ng build --stats-json
webpack-bundle-analyzer dist/stats.json

**Comment by ruucm-working** [comment]
@chinchiheather Thanks!!
