### ISSUE TITLE
Add a default view override option to the config object

### ISSUE THREAD

**Issue by InSuperposition** [th0r/webpack-bundle-analyzer#52]
From both a config object and the cli tool, I'd like the ability to set the initial view for the file size out to be set to 'Gzipped' or any other available option.

Thanks for the great work.

**Comment by valscion** [comment]
Hi, and thanks for the feature request!

I've sometimes also wanted to have such a configuration option, so I get where you're coming from. Unfortunately, with the current approach and architecture doing this change would be a big effort so it won't happen anytime soon.

Should we also at some point support additional visualizations (see #32), this configuration option would have to be special for each visualization.

I don't think we will do this at any time soon, but this is a nice point to consider when we're considering supporting additional visualizations.

**Comment by th0r** [comment]
`defaultSizes` option added in `v2.6.0`
