### ISSUE TITLE
Fails to parse bundle asset.

### ISSUE THREAD

**Issue by ruiaraujo** [th0r/webpack-bundle-analyzer#54]
#### Issue description
I am using the analyser as a plugin to get the gzipped stats.
Recently some code change caused this to happen.

Couldn't parse bundle asset "main-1468dcadd5cb43aed7c5.js".
Analyzer will use module sizes from stats file.

#### Technical info
* Webpack Bundle Analyzer version: 2.3.0
* Webpack version: 2.2.1
* Node.js version: 6.9.2
* npm/yarn version: 4.1.2
* OS: OSX 10.11

#### Debug info
How do you use this module? As CLI utility or as plugin?

As a plugin.

Stats and bundles: https://www.dropbox.com/s/9kbr4lyljlsvqgw/stats%20and%20bundle.zip?dl=0

cc @valscion

**Comment by valscion** [comment]
Thanks for creating the issue :+1:. I don't have time right now to look into this but I will look at this when I do 😊

**Comment by ruiaraujo** [comment]
Thanks for helping with this tool.

BTW I was able to work around the problem by using NamedModulesPlugin when running this plugin.

**Comment by valscion** [comment]
Ok, great to hear that!

**Comment by valscion** [comment]
I can replicate this issue. For some reason, your main bundle files look like this:

```js
webpackJsonp([10], Array(18).concat([ /* ... */]), [968]);
```

As you can see, the `webpackJsonp` has _three_ arguments. I'll have to dig to webpack sources to figure out why this happens... but that is the reason why the current code can't find the modules from your bundle.

**Comment by valscion** [comment]
Ok #56 should fix your issue. I suppose your root cause might've been the same as what @christianalfoni had in https://github.com/th0r/webpack-bundle-analyzer/pull/44#issuecomment-278588447
