### ISSUE TITLE
Shut server down as soon as browser page is opened

### ISSUE THREAD

**Issue by elfey** [th0r/webpack-bundle-analyzer#57]
There should be an option where as soon as the stats are opened in the browser, the server shuts down that way developers can still see their stats and don't have to `ctrl+c` every time they make a build.

**Comment by valscion** [comment]
Thank you for your feature request ☺️ 

I get where you're coming from. I myself kinda like being able to refresh the stats page at will without the server closing down underneath.

I think adding this feature would be a tad too complicated to implement, and we'd want to focus our efforts on something else. I don't think we'd want to maintain it, as it would be quite easy to break by accident and it would require us to come up with full browser-based end-to-end tests to avoid breakage.

**Comment by elfey** [comment]
Just realized you already have a feature similar to this, which generates an HTML file and automatically opens it. That's great, thanks!
