### ISSUE TITLE
Can't use with memory-fs ?

### ISSUE THREAD

**Issue by wenkanglin** [th0r/webpack-bundle-analyzer#58]
#### Issue description
https://webpack.js.org/api/node/#compiling-to-memory

I want to use `webpack-bundle-analyzer` with `memory-fs`, for not output to the specified files on disk. But this will cause error:
```
Couldn't parse bundle asset "F:\projects\businessmap-app\.analyse\scripts\c-condition.c9ded9.js".
```

#### Technical info
* Webpack Bundle Analyzer version: 2.3.1
* Webpack version: 2.2.1
* Node.js version: 7.7.1
* npm/yarn version: 4.1.2
* OS: Windows 7

#### Debug info
How do you use this module? As CLI utility or as plugin?

plugin

If CLI, what command was used? (e.g. `webpack-bundle-analyzer -O path/to/stats.json`)

If plugin, what options were provided? (e.g. `new BundleAnalyzerPlugin({ analyzerMode: 'disabled', generateStatsFile: true })`)

```
new BundleAnalyzerPlugin({
  generateStatsFile: true
})
```

For some reason, I can't provide the full info about webpack config file. Maybe try a demo with `memory-fs` will reproduce the issue. Thx.

**Comment by valscion** [comment]
Hi! Are you able to see the stat sizes anyway? The error you are getting should mean that we aren't able to show you the Gzipped or minified sizes, but you might still be able to see the stat sizes.

The plugin currently reads the bundled files from the filesystem, so I'm afraid we don't (yet) support analyzing in-memory bundles.

This is the first time I've heard of the `.outputFileSystem` configuration option for webpack. It sounds neat — would be nice to see what it would take to support such an approach. It might even mean that this would also be compatible with `webpack-dev-server` at some point?

The optimal situation for running `webpack-bundle-analyzer` is by running it against your production deployment files. **Could you tell me a bit more about your use case?** Why would you want to use this together with `memory-fs`?

**Comment by wenkanglin** [comment]
Yes, it is. This is able to see the stat sizes.
I just want to add a new node command, like: `npm run analyse`, specifically used to analyze the webpack bundle, and don't want to writes the output to the specified files on disk, because the `npm run build` will be used to. So, I use the `outputFileSystem` with `memory-fs` for output files in memory.

**Comment by valscion** [comment]
Ok, thanks! Why don't you want to write the specified files to disk? I'm just curious :)

**Comment by wenkanglin** [comment]
Whenever I run build with below webpack config:
```
module.exports = {
  ...
  plugins: [
    new webpack.CommonsChunkPlugin({
      names: ['vendor', 'manifest'],
      minChunks: Infinite
    })
  ]
};
```
The `manifest` file will change, maybe I just don't want to commit code frequently by git 😊

**Comment by wenkanglin** [comment]
Ask a question: Where is the gzip size from ? I didn't use the gzip

**Comment by valscion** [comment]
> The manifest or source map file will change, maybe I just don't want to commit code frequently by git 😊

Have you considered ignoring those built files from `git` altogether? You don't usually want to want to commit built files to git anyway. See https://help.github.com/articles/ignoring-files/ for more details on ignoring. If you already knew this, then please forgive me, I'm in no way trying to be patronizing.

> Ask a question: Where is the gzip size from ? I didn't use the gzip

The plugin calculates the gzip sizes of your built sources if it can access them, in order to show you more detailed sizes should you use gzip when you're serving your JavaScript files in production ☺️

**Comment by wenkanglin** [comment]
Thank you for answer. Support output in-memory maybe is a good idea 👍
