### ISSUE TITLE
CI Errors, build stage never completes

### ISSUE THREAD

**Issue by elfey** [th0r/webpack-bundle-analyzer#59]
When this package, at its latest versions, is integrated with CircleCI, it gets caught in the build stage.

If this package is removed, the build stage completes successfully.

**Comment by th0r** [comment]
What do you mean?

**Comment by elfey** [comment]
We don't want to use this plugin in CI.

But we like the plugin and would rather not have a separate webpack config just for CI to disable this one thing. We've solved this for now by disabling the `openAnalyzer` feature (we could probably have another workaround that detects operating system and enables/disables the `openAnalyzer` feature if it's not Windows/MacOS... but that still doesn't solve the problem for Linux users.

It would be great if we could figure out why this doesn't work in CI.

**Comment by valscion** [comment]
Hmm so are you generating a static HTML file or opening the server? As the server doesn't close until explicitly closed.

It sounds to me like you indeed want to disable the `openAnalyzer` config option and set `analyzerMode` option to either `disabled` or `static`.

If you do, however, set these options and the CI still doesn't pass, then we might be able to do something. Otherwise, it is more likely an issue with how you have done your CI builds, not in how this plugin is created.

**Comment by elfey** [comment]
We've set it to static, that's why I'm still a little confused about what is going on. I was hoping because the process exits nicely on my computer, that it would in CI. It seems that maybe the process is exiting differently than webpack traditionally does.

**Comment by valscion** [comment]
You need to set `openAnalyzer` to `false` *and* set `analyzerMode` to `"static"`.

Your comment suggest that you're incorrectly setting `openAnalyzer: "static"` which I'm not sure what it does but likely it is perceived the same as setting the value to `true` as in JS a non-empty string is a "truthy value".

**Comment by elfey** [comment]
@valscion my mistake, I worded that incorrectly (it was 3 AM). I did as you described above.

**Comment by valscion** [comment]
Ok, then it does seem weird. It should complete... would you be able to create a reproduction repository that has this issue?

**Comment by valscion** [comment]
Hiya @elfey, do you still have this issue? Would you be able to create a reproduction case for this?

**Comment by chrisui** [comment]
`openAnalyzer: false` worked for us 👍 

Might make a more sensible default.

**Comment by valscion** [comment]
Thanks, @chrisui! I'll close this for now, I can always reopen later if need be.

> Might make a more sensible default.

Thanks for your input :) I don't think we'll be changing the default option for now, though.
