### ISSUE TITLE
Report gzipped size

### ISSUE THREAD

**Issue by jdalton** [th0r/webpack-bundle-analyzer#6]
With [gzip-size](https://www.npmjs.com/package/gzip-size) you could report the gzipped size to complement the minified
(so minified+gzipped size).

**Comment by oliverzy** [comment]
+1
very useful feature

**Comment by boa86** [comment]
+1
interested

**Comment by th0r** [comment]
This is the next thing on my plate. It just requires some work in UI to add module size switcher (stat/parsed/gzipped).

**Comment by th0r** [comment]
Added in `v2.0.0`

**Comment by tleunen** [comment]
@th0r gzip doesn't seem to work in a static mode, do you confirm?
I only see the stat size

**Comment by ericclemmons** [comment]
Noticed the same thing:

```shell
$ webpack --json --profile --sort-modules-by size --sort-chunks-by size --sort-assets-by size > build/stats.json
$ webpack-bundle-analyzer build/stats.json
```

**Comment by valscion** [comment]
Gzip size reporting needs access to your build directory. If your other built files are in the same folder as the `stats.json`, you'll get the GZip sizes automatically. Otherwise you'll need to pass the assets build directory to the CLI with a second parameter.
