### ISSUE TITLE
Does not work with DllReferencePlugin

### ISSUE THREAD

**Issue by lekhnath** [th0r/webpack-bundle-analyzer#60]
#### Issue description
Getting following error message
```
Could't analyze webpack bundle:
TypeError: Cannot read property 'raw' of undefined
Could't find any javascript bundles in provided stats file
```

#### Technical info
* Webpack Bundle Analyzer version: 2.3.1
* Webpack version:2.2.1
* Node.js version:v6.9.5
* npm/yarn version: yarn 0.19.1
* OS: Ubuntu

#### Debug info
How do you use this module? As CLI utility or as plugin?
Plugin

If CLI, what command was used? (e.g. `webpack-bundle-analyzer -O path/to/stats.json`)

If plugin, what options were provided? (e.g. `new BundleAnalyzerPlugin({ analyzerMode: 'disabled', generateStatsFile: true })`)
```
new BundleAnalyzerPlugin({
      analyzerMode: isProduction ? 'server': 'disabled',
      analyzerHost: '10.0.0.50', //I am using vagrant
      analyzerPort: 8888,
      generateStatsFile: false,
      openAnalyzer: false
 })
```
What other Webpack plugins were used?
```
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NamedModulesPlugin(),
    new WebpackNotifier({
      alwaysNotify: false,
      title: 'Hello World',
      contentImage: root('src/assets/images/favicon.ico')
    }),
    new webpack.LoaderOptionsPlugin({
      debug: true
    }),
    new webpack.DefinePlugin({
      'process.env': {
        'ENV': JSON.stringify(ENV)
      }
    }),
    new webpack.DllReferencePlugin({
      context: root('src'),
      manifest: require('build/dll/vendor-manifest.json')
    }),
    new webpack.DllReferencePlugin({
      context: root('src'),
      manifest: require('build/dll/polyfill-manifest.json')
    })
```

**Comment by valscion** [comment]
Hmm this might be interesting. I've never tried DllReferencePlugin so it might be the one causing issues.

Are you able to get the stats successfully if you don't use it?

**Comment by lekhnath** [comment]
If I first genertate `stats.json` file using webpack cli and fed this file to webpack-bundle-analyzer cli , It seems working but cannot figure out why its not working via plugin.

**Comment by valscion** [comment]
Please try running your bundling without the `webpack.DllReferencePlugin` instances in your `plugins` array. It would help in debugging this :)

**Comment by lekhnath** [comment]
Yes, It works when omitting `webpack.DllReferencePlugin` from the plugins list and adding `new BundleAnalyzerPlugin()` instance to the plugins list.

**Comment by valscion** [comment]
Ok great! Could you modify the title of this issue to be this?

> Does not work with DllReferencePlugin

This way the title would be a little less generic than just the analyze error.

**Comment by valscion** [comment]
Hiya @lekhnath, sorry for not getting back to you sooner.

Are you able to generate a `stats.json` file and zip it *with* your built files so we could try to reproduce your error? Alternatively, if you'd be able to whip up a reproduction repository for your issue, that would also be ace! 💞

**Comment by lekhnath** [comment]
@valscion Today I give it another try and surprised to see that there is no issue at all. It is working like a charm even with DllReferencePlugin. I've done lots of changes to my configuration and code in the meantime though. I would open a new issue with reproduction if it encountered again. 
Thanks.

**Comment by valscion** [comment]
Ok, thanks for following up!

**Comment by vjpr** [comment]
I am having issues with trying to get the AutoDLL plugin output to show up.

**Comment by valscion** [comment]
Please open a new issue @vjpr and fill the issue template
