### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by andersekdahl** [th0r/webpack-bundle-analyzer#63]
Just wanted to say that this tool is incredible. The content of our bundles have been a black box but with webpack-bundle-analyzer it's super clear what goes where and we can finally optimize it!

**Comment by andersekdahl** [comment]
Closing since this isn't really an issue. 😄

**Comment by th0r** [comment]
@andersekdahl Thanks for the kind words!

**Comment by nashwaan** [comment]
@th0r A big thank you for this package.
👍👍👍👍👍
