### ISSUE TITLE
webpack.NamedChunksPlugin breaks parsing

### ISSUE THREAD

**Issue by hjeti** [th0r/webpack-bundle-analyzer#67]
When using the webpack.NamedChunksPlugin the bundle can't be parsed anymore by the analyzer. 

`Couldn't parse bundle asset "dist\version\1493729489528\js\app.js".`

If I disable the plugin everything works like a charm.

Attached a bundle that can't be parsed.
[app.txt](https://github.com/th0r/webpack-bundle-analyzer/files/970479/app.txt)

**Comment by valscion** [comment]
Hmm interesting. Would you be able to provide a `stats.json` as well, @hjeti ?

**Comment by valscion** [comment]
Instructions for generating a `stats.json` were in the issue template:

It would be nice to also attach webpack stats file.
It can be generated using these options:
```js
new BundleAnalyzerPlugin({
  analyzerMode: 'disabled',
  generateStatsFile: true,
  // Excludes module sources from stats file so there won't be any sensitive data
  statsOptions: { source: false }
})`
```
`stats.json` will be created in Webpack bundle output directory.

Zip the contents of your bundle directory and upload them here so we have all the pieces necessary for debugging this :)

**Comment by hjeti** [comment]
I couldn't upload a zip (We don't support that file type.) so I have uploaded it to wetransfer. 

https://wetransfer.com/downloads/36dc814a5d80c97a77c112ba0ad07b6020170502131503/e0aa2fde1c0ba9e6ce2b20cb14a16b7120170502131503/2dc762

**Comment by chrisui** [comment]
@valscion FYI I'm still seeing this issue after updating to 2.4.1

`Couldn't parse bundle asset "~/build/vendor.1fb1fe7bbfafd8be0b4b.js".`
