### ISSUE TITLE
Tree shaking problem

### ISSUE THREAD

**Issue by mattcolman** [th0r/webpack-bundle-analyzer#76]
#### Issue description
I am using UglifyJsPlugin *before* the BundleAnalyzerPlugin.
I confirm that bundling my code with UglifyJsPlugin is tree shaking certain modules, but those modules still appear in the visualisation from BundleAnalyzerPlugin.

#### Technical info
* Webpack Bundle Analyzer version: 2.8.1
* Webpack version: 2.5.1
* Node.js version:
* npm/yarn version:
* OS:

#### Debug info
How do you use this module? As CLI utility or as plugin? Plugin.

If plugin, what options were provided? No options.

**Comment by th0r** [comment]
> I am using UglifyJsPlugin before the BundleAnalyzerPlugin.

What do you mean by that? If you're taking about the order in the `plugins` array then it doesn't matter.

> I confirm that bundling my code with UglifyJsPlugin is tree shaking certain modules

Could you provide a simple reproduction repo?

**Comment by mattcolman** [comment]
Hi @th0r,

Yes I mean't the order in the plugins array.

I have created a simple reproduction repo and thanks for the suggestion because I think it's revealed that tree-shaking in webpack is just less affective than I thought, and that webpack-bundle-analyzer is working perfectly. 

If you're interested the repo is here https://github.com/mattcolman/tree-shaking-test
It reveals that by importing `polished` and not using it all, some of it gets tree-shaken but a good chunk of it still remains. This was surprising to me as my understanding of tree-shaking was that unused imports get removed completely.

Anyway I'll send it to `polished` to see what they say. 

Thanks!

**Comment by mattcolman** [comment]
Update: I found https://github.com/styled-components/babel-plugin-polished which compiles away polished helpers and does exactly what I expected. Problem solved. Thanks! webpack-bundle-analyzer is great 👍
