### ISSUE TITLE
Don't generate state.json

### ISSUE THREAD

**Issue by sheweichun** [th0r/webpack-bundle-analyzer#8]
I do like beblow
```
new BundleAnalyzerPlugin({
	        	startAnalyzer:false,
	        	generateStatsFile:true,
	        	statsFilename:'stats.json'
	        })
```
after building completed,I don't find states.json,why?

**Comment by th0r** [comment]
It should be in the same folder as your generated bundles.
Are you sure you added `new BundleAnalyzerPlugin()` to the proper place in your config?
It should be in `plugins` array.

**Comment by sheweichun** [comment]
yeah,I read source code,I just want it to be in the root folder,so change statsFilename to '../stats.json',Thank for your reply
