### ISSUE TITLE
Saving the report to root

### ISSUE THREAD

**Issue by ViggoV** [th0r/webpack-bundle-analyzer#84]
#### Issue description
When running the plugin in development (using webpack dev server) the report is stored in root, rather than the webpack output folder (/public/webpack/ in my case). This has led to some frustration since it is constantly messes with git.

#### Technical info
* Webpack Bundle Analyzer version: 2.8.1
* Webpack version: 2.5.1
* Node.js version: 6.9.1
* npm/yarn version: 4.4.4
* OS: Mac OS 10.12.4

#### Debug info
How do you use this module? As CLI utility or as plugin?

Plugin

new BundleAnalyzerPlugin({
      analyzerMode: 'static',
      openAnalyzer: false,
      reportFilename: 'development_report.html'
})

What other Webpack plugins were used?
StatsPlugin
ExtractTextPlugin
ProvidePlugin
CommonsChunkPlugin
EnvironmentPlugin
LoaderOptionsPlugin

+ in production
NoEmitOnErrorsPlugin
BabiliPlugin

**Comment by valscion** [comment]
Does it output the report in the correct place if you are not using `webpack-dev-server`? If you have set `output.path` setting in your `webpack-dev-server` configuration, this plugin should respect that and output the report inside that directory.

**Comment by ViggoV** [comment]
Yes. If I build via command line the report is generated in the correct location. I can't seem to find an `output.path` option for DevServer. Do you mean the general `output.path` in the webpack config file? That one should be set correctly.

Thank you for the fast reply.

**Comment by valscion** [comment]
Ah, seems like this is the same issue as #75 and was fixed by #79 that is in version `v2.8.2`. So just upgrade your version of `webpack-bundle-analyzer` and it should work :relaxed:

**Comment by ViggoV** [comment]
Awesome! That was it!
Thanks for great help for a great tool :)

**Comment by valscion** [comment]
Great to hear that this got fixed without us having to touch any code :smile:
