### ISSUE TITLE
Parsed size not working

### ISSUE THREAD

**Issue by jmbelloteau** [th0r/webpack-bundle-analyzer#88]
#### Parsed size not working
The returned size for each package is the exact size of the non **Stat size**, even with this code in the options: `defaultSizes: 'parsed'`

#### Technical info
* Webpack Bundle Analyzer version: **v2.8.2**
* Webpack version: **v2.6**
* Node.js version: **v8.1.1**
* npm/yarn version: **v0.24.6**
* OS: **mac OSX Sierra 10.12.5**

#### Debug info
I'm using this module as a **plugin** with this code: `new BundleAnalyzerPlugin()`

#### Others plugins:
- Provide Plugin
- Commons Chunk Plugin
- Source Map Dev Tool Plugin
- Extract Text Plugin
- Style Lint Plugin
- Friendly Errors Webpack Plugin
- Webpack Notifier Plugin
- Progress Bar Plugin
- Clean Webpack Plugin
- Uglify Js Plugin
- Assets Webpack Plugin

#### Stats.json
my [stats.json](https://gist.github.com/jmbelloteau/2cbb530b2b0b95922372aecbe844f968) output from this config

**Comment by th0r** [comment]
Could you send your console output? Does it contain any messages from bundle analyzer?

**Comment by jmbelloteau** [comment]
```bash
npm run start

> jmbelloteau@1.0.1 start /Users/jim/Sites/jmbelloteau
> babel-node webpack/start-app.js

  BUILD ████████████████ 100% (6.9 seconds)

 DONE  Compiled successfully in 12747ms                                                 12:50:34 PM

Build completed in 11.431s

chunk    {0} js/photos.ddd4269c.js (photos) 102 kB {10} [initial] [rendered]
chunk    {1} js/videos.ba6ff489.js (videos) 9.18 kB {10} [initial] [rendered]
chunk    {2} js/stories_post.ab9829ad.js (stories_post) 6.01 kB {10} [initial] [rendered]
chunk    {3} js/stories_list.8c4190fa.js (stories_list) 3.81 kB {10} [initial] [rendered]
chunk    {4} js/maintenance.749e1b55.js (maintenance) 4.09 kB {10} [initial] [rendered]
chunk    {5} js/home.9223242f.js (home) 5.01 kB {10} [initial] [rendered]
chunk    {6} js/errors.2c33dc2d.js (errors) 4.08 kB {10} [initial] [rendered]
chunk    {7} js/about.5fa0cc83.js (about) 4.26 kB {10} [initial] [rendered]
chunk    {8} js/inline.ee357d94.js, css/inline.77a6890c.css (inline) 69 bytes {10} [initial] [rende
red]
chunk    {9} js/app.19652f17.js, css/app.167dffd4.css (app) 69 bytes {10} [initial] [rendered]
chunk   {10} js/vendors.eb44cc2e.js (vendors) 1.23 MB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 17.5 kB [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 364 kB [entry] [rendered]
Webpack Bundle Analyzer is started at http://127.0.0.1:8888
Use Ctrl+C to close it
```

**Comment by jmbelloteau** [comment]
As you can see there is no error message from bundle analyzer, but you know what the problem is resolve 👍 ... I've just upgrade all my packages to last version. Probably some conflict somewhere that disappeared with the upgrade. Tanks anyway

**Comment by th0r** [comment]
OK, closing then
