### ISSUE TITLE
feat: exclude entries

### ISSUE THREAD

**Issue by joscha** [th0r/webpack-bundle-analyzer#9]
Would you accept a PR that allows the bundle analyzer to ignore an entry point?

We currently have two entry points - one with `.min.js` and one without. The one with, we send through uglify, the other we don't. The resulting report looks like this: https://aui-cdn.atlassian.com/atlaskit/pr/stats/d8f6cfdb199abff6c0af668b6da94db6c14b64d1/ak-editor-toolbar-text-formatting/with-deps.html but as you can see the information is duplicated.

Webpack looks something like this:
```js
.entry = {
  'dist/bundle-with-deps.js': productionConfig.entry['dist/bundle.js'],
  'dist/bundle-with-deps.min.js': productionConfig.entry['dist/bundle.js'],
};
```

**Comment by th0r** [comment]
Well, actually, they shouldn't be the same if analyzer was able to parse them successfully.
But what I can see from your report is that it uses module sizes from stats file, not parsed ones.
How are you generating it?

**Comment by joscha** [comment]
I think they show up as different, because the minification is done based on the entry name.

The definition for the two entry points is here: https://bitbucket.org/atlassian/atlaskit/src/79df5c87f48ac9f9d32ce086e503bdf5a7876053/build/webpack/production-cjs.js?at=master&fileviewer=file-view-default

As you can see they refer to the same entry (`dist/bundle.js`) and then two plugins are pushed to the config:

https://bitbucket.org/atlassian/atlaskit/src/79df5c87f48ac9f9d32ce086e503bdf5a7876053/build/webpack/production.js?at=master&fileviewer=file-view-default

that make them different (but only in the sense that one is minified and the other one is not). The base for them (e.g. the source) is exactly the same.

**Comment by th0r** [comment]
@joscha Have you tried the latest version? Are reports for your entry points still the same?

**Comment by joscha** [comment]
We are on `1.5.3` - is that the version you are talking about?

**Comment by th0r** [comment]
Yes

**Comment by joscha** [comment]
yes, still happens: https://aui-cdn.atlassian.com/atlaskit/pr/8b0d99bb34b8260242bc8269b51f670b4e3de434/2016-11-21_10_11_10/stats/ak-avatar/cjs.html

**Comment by valscion** [comment]
Closing this issue as #72 likely resolved this as well.
