### ISSUE TITLE
Feature request: show build time

### ISSUE THREAD

**Issue by tashburn** [th0r/webpack-bundle-analyzer#93]
I'd like to use this to find what's taking up so much build time for my webpack build -- which isn't the same as file size. Any chance you want to add that metric in addition to the file sizes?

**Comment by valscion** [comment]
Hmm I wonder if it is at all possible to extract that information from the webpack build pipeline. Would you be open to researching whether it's possible? I don't think webpack's stats.json has that information readily available so it would probably need some trickery to get it.

It'd be nice if that was possible to do :). It might be better to implement that feature outside of this package, as we mostly want to provide insight about the size of the resulting code and don't (yet at least) care about how that result came to be.

**Comment by tashburn** [comment]
I'm afraid I don't have the bandwidth for that.

**Comment by valscion** [comment]
I'm afraid neither will us.
