### ISSUE TITLE
Can't parse bundle asset with babel-preset-env on latest browsers

### ISSUE THREAD

**Issue by imathews** [th0r/webpack-bundle-analyzer#94]
#### Issue description
I'm getting the "Can't parse bundle asset" error (and therefore am only seeing stat sizes) when I adjust my `babel-preset-env` parameters to only support the latest browser versions (specifically, Safari 10.1). The big change here (compared to Safari 10.0, which works as expected) is that babel is using native async/await.

Bizarrely, the parse _does succeed_ on 10.1 if I set devtool to 'eval-source-map'. If I set it to null, or 'source-map', I get this error. Not entirely sure why this would be the case, but happy to throw additional logs in to help better debug...

#### Technical info
* Webpack Bundle Analyzer version: `2.8.2`
* Webpack version: `3.1.0`
* Node.js version: `7.10.0`
* npm/yarn version: `4.2.0`
* OS: `MacOS 10.12.4`

#### Debug info
I use this module as a plugin: 
```js
new BundleAnalyzerPlugin({
        analyzerMode: 'server',
	reportFilename: `${logDirectory}/statistics.html`,
	analyzerHost: 'localhost',
	analyzerPort: 9081,
	defaultSizes: 'gzip',
	openAnalyzer: true,
	generateStatsFile: true,
	logLevel: 'info',
        statsOptions: { source: false },
})
```

I'm able to reproduce this without any additional plugins. I use `babel-loader` with the following options:
```js
{
	test: /\.jsx?$/,
	exclude: /node_modules/,
	loader: 'babel-loader',
	query: {
		presets: [
			['env', {
				targets: {
					safari: '10.1',   // change to '10.0' and bundle parse succeeds
					edge: '15',
					firefox: '54',
					chrome: '60',
				},
			        modules: false,
			        loose: true,
		        }],
		],
		plugins: [
			'syntax-dynamic-import',
			'transform-class-properties',
			'transform-object-rest-spread',
			'transform-react-jsx',
		],
	},
}
```

[stats.json.txt](https://github.com/th0r/webpack-bundle-analyzer/files/1136848/stats.json.txt)

**Comment by valscion** [comment]
Thanks! Seems like the bundle parsing fails somehow with this combination. Are you able to upload the compiled bundles as well? That way we could more easily verify this case.

**Comment by imathews** [comment]
sorry I couldn't get you an example — got bogged down with things. Thanks @th0r for hoping on this!
